name: Run Selenium + REST Assured Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3 - Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4 - Run tests
      - name: Run TestNG tests
        run: mvn clean test

      # Step 5 - Upload Extent Report as artifact
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: reports/
